Repository TimeChimp/tacugama, pull requests merged in 2021-01, with the labels that each got.

#122 Add CharCounter component
  package-lock.json
  package.json
  src/components/char-counter/CharCounter.stories.tsx
  src/components/char-counter/CharCounter.tsx
  src/components/char-counter/index.ts
  src/components/index.ts
  src/components/input/Input.stories.tsx
  src/components/input/Input.tsx
  src/models/Theme.ts
  src/theme/colors.ts
  src/theme/overrides.ts
Labels: enhancement

#123 Add additional test ids
  package-lock.json
  package.json
  src/components/button/Button.stories.tsx
  src/components/button/Button.tsx
  src/components/button/ModalButton.tsx
  src/components/input/Input.stories.tsx
  src/components/input/Input.tsx
Labels: enhancement

#144 Auto create / publish release
  .github/pr-labeler-config.yml
  .github/release-drafter.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/release.yml
  package.json
Labels: feature

#145 Bump release drafter version
  .github/release-drafter.yml
  .github/workflows/release.yml
Labels: feature

#149 Add missing design system colors
  .github/workflows/release.yml
  package.json
  src/models/Theme.ts
  src/theme/colors.ts
Labels: feature

#151 Updated icons with color prop
  src/components/icons/ActionMenu.tsx
  src/components/icons/ActionMenuActive.tsx
  src/components/icons/BottomArrow.tsx
  src/components/icons/Calendar.tsx
  src/components/icons/CalendarDay.tsx
  src/components/icons/CalendarDayActive.tsx
  src/components/icons/CalendarWeek.tsx
  src/components/icons/CalendarWeekActive.tsx
  src/components/icons/Camera.tsx
  src/components/icons/Check.tsx
  src/components/icons/LeftArrow.tsx
  src/components/icons/Location.tsx
  src/components/icons/Logout.tsx
  src/components/icons/NotesDisabled.tsx
  src/components/icons/NotesEmpty.tsx
  src/components/icons/NotesFull.tsx
  src/components/icons/Pencil.tsx
  src/components/icons/ReturnArrow.tsx
  src/components/icons/RightArrow.tsx
  src/components/icons/Settings.tsx
  src/components/icons/TcClock.tsx
  src/components/icons/Trash.tsx
  src/components/icons/TrashFull.tsx
  src/components/icons/Undo.tsx
  src/components/icons/Warning.tsx
Labels: feature

#152 Added down up icons for sorting
  package.json
  src/components/icons/index.ts
Labels: feature

#153 Fix/csr 000/fixed icons updown
  package.json
  src/components/icons/TriangleDown.tsx
  src/components/icons/TriangleUp.tsx
  src/components/icons/index.ts
Labels: bug
