Repository TimeChimp/tacugama, pull requests merged in 2021-02, with the labels that each got.

#162 Add data grid component
  package-lock.json
  package.json
  src/components/data-grid/DataGrid.stories.tsx
  src/components/data-grid/DataGrid.tsx
  src/components/data-grid/Filters.tsx
  src/components/data-grid/HeaderCheckbox.tsx
  src/components/data-grid/NoRowsTemplate.tsx
  src/components/data-grid/RowActionsCell.tsx
  src/components/data-grid/StatusBarRowCount.tsx
  src/components/data-grid/StyledDataGrid.ts
  src/components/data-grid/defaultFormatSettings.ts
  src/components/data-grid/index.ts
  src/components/data-grid/types.ts
  src/components/index.ts
Labels: feature

#163 Remove direct css imports
  package.json
  src/components/data-grid/DataGrid.stories.tsx
  src/components/data-grid/DataGrid.tsx
Labels: bug

#170 Add flex item
  src/components/flex-item/FlexItem.stories.tsx
  src/components/flex-item/FlexItem.tsx
  src/components/flex-item/StyledFlexItem.tsx
  src/components/flex-item/index.ts
  src/components/index.ts
  src/models/TextAlignProperty.ts
  src/models/index.ts
Labels: feature

#179 Allow page title to be optional or string
  src/components/page-layout/PageLayout.stories.tsx
  src/components/page-layout/PageLayout.tsx
Labels: bug

#182 Fix custom colors
  src/models/Theme.ts
  src/theme/colors.ts
Labels: bug

#183 Add account icons
  src/components/icons/Account.tsx
  src/components/icons/Flag.tsx
  src/components/icons/Lock.tsx
  src/components/icons/icons.stories.tsx
  src/components/icons/index.ts
Labels: feature

#184 Fix radio styling
  package.json
  src/components/radio/RadioItem.tsx
Labels: bug

#185 Update radio styling
  package.json
  src/components/radio/RadioItem.tsx
Labels: bug

#186 Remove unnecessary dependencies
  package-lock.json
  package.json
Labels: dependencies

#187 Add custom cell loader to data grid
  package.json
  src/components/data-grid/DataGrid.tsx
  src/components/data-grid/LoadingCellTemplate.tsx
Labels: feature

#190 Add data grid access token
  package-lock.json
  package.json
  src/components/data-grid/DataGrid.tsx
  src/components/data-grid/types.ts
Labels: feature

#191 Fix data grid headers
  package.json
  src/components/data-grid/DataGrid.tsx
Labels: bug

#192 Update no items placeholder
  package.json
  src/components/data-grid/DataGrid.tsx
  src/components/data-grid/NoRowsTemplate.tsx
Labels: feature

#193 Fix continue loading when no results
  package.json
  src/components/data-grid/DataGrid.tsx
Labels: bug

#204 Add unit tests
  .gitignore
  jest.config.ts
  package-lock.json
  package.json
  src/components/avatar/Avatar.stories.tsx
  src/components/avatar/Avatar.test.tsx
  src/components/char-counter/CharCounter.test.tsx
  src/components/checkbox/Checkbox.tsx
  src/components/data-grid/DataGrid.test.tsx
  src/components/data-grid/Filters.tsx
  src/components/data-grid/HeaderCheckbox.tsx
  src/components/data-grid/LoadingCellTemplate.tsx
  src/utils/test-utils.tsx
  tsconfig.json
Labels: feature

#208 feat: add en-gb as supported language
  package-lock.json
  package.json
  src/components/data-grid/types.ts
  src/types/SupportedLocale.ts
  src/utils/get-date-locale.ts
Labels: feature

#209 fix: separate skeleton and loader in select
  package.json
  src/components/select/Select.stories.tsx
  src/components/select/Select.test.tsx
  src/components/select/Select.tsx
  src/theme/colors.ts
Labels: feature

#210 fix: page layout top padding
  package.json
  src/components/page-layout/StyledPageLayout.tsx
Labels: bug

#211 feat: add separator component
  package.json
  src/components/index.ts
  src/components/separator/Separator.stories.tsx
  src/components/separator/Separator.tsx
  src/components/separator/index.ts
Labels: feature

#212 Add noBorder prop to box
  package.json
  src/components/box/Box.stories.tsx
  src/components/box/Box.tsx
Labels: bug

#215 fix: jsx / tsx eslint config
  .eslintrc.json
  package-lock.json
  package.json
  src/components/block/index.ts
  src/components/progress-bar/index.ts
  src/components/select/Select.tsx
  src/components/select/index.ts
  tsconfig.json
Labels: bug

#213 Feat/csr 799/toggle component
  package.json
  src/components/data-grid/DataGrid.stories.tsx
  src/components/data-grid/DataGrid.tsx
  src/components/data-grid/HeaderColumnToggle.tsx
  src/components/data-grid/StyledDataGrid.ts
  src/components/data-grid/types.ts
  src/components/dropdown/Dropdown.tsx
  src/components/dropdown/DropdownOption.tsx
  src/components/dropdown/StyledDropdownOption.ts
  src/components/icons/Cog.tsx
  src/components/icons/index.ts
  src/components/input/SearchInput.tsx
  src/components/input/index.ts
Labels: feature

#223 fix: separator export
  src/components/separator/Separator.stories.tsx
  src/components/separator/Separator.tsx
  src/components/separator/styles.ts
Labels: bug

#224 feat: add configurable avatar component
  package.json
  src/components/avatar/Avatar.stories.tsx
  src/components/avatar/Avatar.tsx
  src/components/avatar/ConfigurableAvatar.test.tsx
  src/components/avatar/ConfigurableAvatar.tsx
  src/components/avatar/index.ts
  src/components/avatar/styles.ts
  src/components/button/RoundButton.tsx
  src/components/button/index.ts
  src/components/icons/ImagePlaceholder.tsx
  src/components/icons/index.ts
Labels: feature

#230 fix: avatar issues
  package.json
  src/components/avatar/Avatar.tsx
  src/components/avatar/ConfigurableAvatar.tsx
  src/components/button/RoundButton.tsx
Labels: bug

#237 feat: add msw to storybook
  .storybook/preview.js
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/components/data-grid/DataGrid.stories.tsx
  src/components/data-grid/DataGrid.test.tsx
  src/components/data-grid/mockServer.ts
Labels: feature

#238 fix: search component styling
  package.json
  src/components/data-grid/Filters.tsx
  src/components/input/Input.stories.tsx
  src/components/input/Input.tsx
  src/components/input/SearchInput.tsx
Labels: bug
